on: push
name: Check
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      F90: gfortran
      F90_VENDOR: GNU
      PFUNIT: /usr/local
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install tzdata
          sudo apt-get install -y  --no-install-recommends \
              cmake \
              python3 \
              libpython3-dev \
              python3-dev \
              python3-setuptools \
              python3-pip \
              python3-cffi \
              python3-numpy \
              cython3


          curl -L https://github.com/Goddard-Fortran-Ecosystem/pFUnit/archive/3.2.9.tar.gz | tar xz
          cd pFUnit-3.2.9 && \
              cmake . && \
              make &&\
              sudo make install INSTALL_DIR=${PFUNIT}
      - name: build and test
        run: VERBOSE=1 make check
